### ISSUE TITLE
Z3 backend installation instructions

### ISSUE THREAD

**Issue by toeklk** [gsdlab/ClaferIDE#14]
Right now, the Z3 backend installation instructions read

> Backend: ClaferZ3
> This assumes you use the default configuration <target directory>/ClaferIDE/Server/Backends/backends.json file.
>  Refer to the ClaferZ3 installation requirements. This should install Python 3, PIP and Z3.
> Install ClaferZ3 into the folder <target directory>/ClaferZ3.

At least for me this does not work on Mac OS X (yosemite), probably due to the fact that claferSMT.sh currently requires to be executed from the directory where the .egg file resides.

A quick and (very) dirty workaround is to modify the shell script and add absolute locations...

```patch
 git diff
diff --git a/claferSMT.sh b/claferSMT.sh
index b80193d..d429632 100755
--- a/claferSMT.sh
+++ b/claferSMT.sh
@@ -1,11 +1,10 @@
 #!/bin/bash
 
 # Run ClaferSMT.egg
-
-export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH
+export DYLD_LIBRARY_PATH=/Users/kgad/install/clafer/lib:$DYLD_LIBRARY_PATH
 export PATH=`pwd`:$PATH
 PYTHON3=python3
 
 if [ "$OS" = "Windows_NT" ]; then PYTHON3=python; fi
 
-"$PYTHON3" ClaferSMT.egg $@
+"$PYTHON3" /Users/kgad/install/clafer/ClaferSMT.egg $@
```

**Comment by mantkiew** [comment]
Fixed on the ClaferSMT side in the [commit](https://github.com/gsdlab/ClaferSMT/commit/bd247fcd71bffc6278d8a60f7b1047b174e4099d).
