### ISSUE TITLE
ChocoSolver backend

### ISSUE THREAD

**Issue by toeklk** [gsdlab/ClaferIDE#15]
The backends.json file refers to a claferChocoIG.sh shell script in order to start the ChocoSolver backend.  However, it seems like the code at https://github.com/gsdlab/ClaferChocoIG does not contain such a shell script?

**Comment by mantkiew** [comment]
Yes, that is just an artifact coming from our internal deployment. It just contains

```
#!/bin/bash
java -jar ~/bin/claferchocoig-0.3.6.1-jar-with-dependencies.jar $@
```

I'll update the instructions to use `java -jar` directly.
